name: Prettier
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: npm install
        run: npm install
      - name: Run Prettier
        run: npx prettier --check .
